RUNBOOKS = {
    "database": "RB-DB-04 · Database saturation and failover",
    "network": "RB-NET-02 · Connectivity and packet-loss triage",
    "authentication": "RB-IAM-03 · Identity provider degradation",
    "deployment": "RB-REL-01 · Release rollback and verification",
    "compute": "RB-CMP-05 · Compute capacity and memory pressure",
    "security": "RB-SEC-07 · Credential exposure containment",
}

EXAMPLES = {
    "database": [
        "Checkout requests time out while postgres connections are exhausted",
        "Primary database replica lag climbed above ten minutes",
        "Orders API reports deadlocks and slow SQL queries",
        "Redis cache evictions caused repeated database reads",
        "Database disk space is nearly full and writes are failing",
        "RDS failover left the application using a stale endpoint",
        "Connection pool is saturated during the payment traffic spike",
        "Migration locked the customers table and increased query latency",
        "MongoDB replica set has no elected primary",
        "Read replica CPU is high and analytics queries are timing out",
    ],
    "network": [
        "Services in the private subnet cannot reach the internet gateway",
        "Packet loss between two availability zones is causing retries",
        "DNS resolution intermittently fails inside the Kubernetes cluster",
        "Load balancer health checks fail although pods are healthy",
        "VPN tunnel dropped and the branch office is unreachable",
        "Firewall rule blocks outbound traffic on port 443",
        "Customers receive gateway timeout from the edge proxy",
        "Service mesh reports TLS handshake errors between workloads",
        "NAT gateway route is missing after the infrastructure change",
        "Ingress controller returns connection reset for websocket traffic",
    ],
    "authentication": [
        "Users cannot sign in because OAuth token exchange is failing",
        "SAML login loops back to the identity provider",
        "JWT validation rejects valid sessions after key rotation",
        "Multi factor authentication codes are delayed for all employees",
        "Service account receives access denied from the cloud API",
        "Single sign on sessions expire immediately after login",
        "Identity provider latency prevents admin portal access",
        "Refresh tokens are invalid following the certificate rotation",
        "Role mapping removed permissions from the support team",
        "Login callback has an invalid redirect URI in production",
    ],
    "deployment": [
        "New release caused a spike in five hundred errors after rollout",
        "Canary version fails readiness probes in production",
        "Helm upgrade is stuck because the deployment cannot progress",
        "Latest frontend build serves blank pages to customers",
        "Rollback completed but old pods still receive traffic",
        "Container image tag points to the wrong application version",
        "Feature flag enabled broken checkout logic after deployment",
        "Database migration failed during the release pipeline",
        "GitHub Actions deployed configuration to the wrong environment",
        "New API release is incompatible with the mobile client",
    ],
    "compute": [
        "Worker pods are being killed because memory limits are exceeded",
        "Kubernetes nodes are unschedulable due to CPU pressure",
        "Autoscaler did not add capacity during the traffic surge",
        "Background jobs are stuck after the queue workers crashed",
        "Serverless functions hit the concurrency limit",
        "Application process leaks memory and restarts every hour",
        "Virtual machine is unresponsive with load average above thirty",
        "GPU inference workers cannot allocate enough memory",
        "Batch processing consumed all ephemeral disk on the node",
        "Container is crash looping after an out of memory termination",
    ],
    "security": [
        "Public repository contains a leaked production API token",
        "Unusual login activity suggests a compromised administrator account",
        "Web application firewall detected repeated SQL injection attempts",
        "Malware alert triggered on a customer support workstation",
        "Cloud storage bucket was accidentally made public",
        "Secret scanner found credentials committed to source control",
        "Audit logs show privilege escalation by an unknown user",
        "Certificate private key may have been exposed in build logs",
        "Endpoint protection quarantined ransomware on a server",
        "Suspicious outbound traffic is leaving the production cluster",
    ],
}

INCIDENTS = [
    {"id": "INC-4821", "text": "Checkout timed out after postgres connection pool saturation", "category": "database", "resolution": "Raised pool ceiling temporarily, terminated idle sessions, then tuned query timeouts."},
    {"id": "INC-4764", "text": "DNS lookup failures between payment services", "category": "network", "resolution": "Rolled back CoreDNS config and verified cross-zone resolution."},
    {"id": "INC-4702", "text": "JWT sessions rejected after signing key rotation", "category": "authentication", "resolution": "Restored previous JWKS, warmed caches, then repeated rotation with overlap."},
    {"id": "INC-4658", "text": "Recommendation pods OOM killed during traffic peak", "category": "compute", "resolution": "Scaled replicas and corrected memory requests before profiling the leak."},
    {"id": "INC-4590", "text": "Canary release returned elevated five hundred errors", "category": "deployment", "resolution": "Aborted rollout automatically and reverted the incompatible API change."},
    {"id": "INC-4517", "text": "Secret exposed in public CI build output", "category": "security", "resolution": "Revoked credential, restricted log access, rotated dependents, and reviewed audit history."},
]

